name: Docker Image CI

on:
  push:
    branches: [ swigaroo ]
  pull_request:
    branches: [ swigaroo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opensim:$(date +%s)
